import { Header } from '@organism/Header'
import './globals.css'
import { Trpcclient } from './TrpcClient'


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const palitanAngMenu = () => {
    return <Header />;
  }

  return (
    <Trpcclient>
      <html lang="en">
        <head>
          <title>Twitter</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </head>
        <body>
          <div>
          {/* { 
              palitanAngMenu
          } */}
          </div>
          
          <main className="mx-auto w-pc">{children}</main>
        </body>
      </html>
    </Trpcclient>
  )
}
